version: '3.8'

services:
  page_analyzer:
    image: postgres:latest
    container_name: page_analyzer
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DOCKER_PORT}:5432
    restart: always